# Generated by Django 4.2.2 on 2023-06-27 15:21

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=500, null=True)),
                ('token', models.TextField(default=uuid.UUID('982c33a9-f947-4210-9b2b-87957a594f1a'))),
                ('send_at', models.DateTimeField(default=datetime.datetime.utcnow, null=True)),
                ('is_expired', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InvitationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=128)),
                ('full_name', models.CharField(max_length=200, null=True)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invitations.baseinvitation')),
            ],
        ),
    ]
