# Generated by Django 4.2.2 on 2023-07-16 08:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_department_company'),
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinvitation',
            name='token',
            field=models.TextField(default=uuid.UUID('4daa1614-6786-465e-82dc-759748fb29e1')),
        ),
        migrations.AlterField(
            model_name='invitationinfo',
            name='invitation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_info', to='invitations.baseinvitation'),
        ),
        migrations.CreateModel(
            name='EmployeeInvitation',
            fields=[
                ('baseinvitation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='invitations.baseinvitation')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='company.department')),
            ],
            bases=('invitations.baseinvitation',),
        ),
    ]
