# Generated by Django 4.2.2 on 2023-06-30 12:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0002_alter_baseinvitation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinvitation',
            name='token',
            field=models.TextField(default=uuid.UUID('d5cac121-5823-4070-8599-e437e2199119')),
        ),
    ]
