# Generated by Django 4.2.2 on 2023-09-26 18:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0002_alter_baseinvitation_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinvitation',
            name='token',
            field=models.TextField(default=uuid.UUID('f969136a-d150-4b85-96aa-11664d426969')),
        ),
    ]
