# Generated by Django 4.2.2 on 2023-09-26 19:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0003_alter_baseinvitation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinvitation',
            name='token',
            field=models.TextField(default=uuid.UUID('951712e6-543d-4995-8221-e55d94e0e6fb')),
        ),
    ]
