# Generated by Django 4.2.2 on 2023-07-01 18:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0003_alter_baseinvitation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinvitation',
            name='token',
            field=models.TextField(default=uuid.UUID('d3fd879b-4893-4d56-b2ea-a84f334dd011')),
        ),
    ]
