# Generated by Django 4.2.2 on 2023-07-08 11:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0005_alter_baseinvitation_token_employeeinvitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitationinfo',
            name='invitation',
        ),
        migrations.AddField(
            model_name='baseinvitation',
            name='invitation_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invitations.invitationinfo'),
        ),
        migrations.AlterField(
            model_name='baseinvitation',
            name='token',
            field=models.TextField(default=uuid.UUID('befa38bd-66b0-4d35-b98b-fef86781bf1e')),
        ),
    ]
