# Generated by Django 4.2.2 on 2023-06-27 15:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('role', models.IntegerField()),
                ('subrole', models.IntegerField()),
                ('first_name', models.CharField(blank=True, max_length=128, null=True)),
                ('last_name', models.CharField(blank=True, max_length=128, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('member_since', models.DateTimeField(default=datetime.datetime.utcnow, null=True)),
                ('last_seen', models.DateTimeField(default=datetime.datetime.utcnow, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('first_connection', models.BooleanField(default=True)),
                ('welcome_msg', models.BooleanField(default=True)),
                ('permissions', models.CharField(default='', max_length=10000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=500, unique=True)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.baseuser')),
                ('info_deleted', models.BooleanField(default=False)),
                ('accept_medical_sharing', models.BooleanField(default=False)),
                ('assigned_to_company', models.BooleanField(default=False)),
                ('update_email', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.department')),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.baseuser',),
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexe', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=50)),
                ('age', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('tall', models.IntegerField()),
                ('profession', models.CharField(max_length=200)),
                ('home_work', models.CharField(choices=[('Frequently', 'Frequently'), ('SomeTimes', 'SomeTimes'), ('Always', 'always'), ('NoHomeWork', 'NoHomeWork')], default='Frequently', max_length=50)),
                ('sleep', models.FloatField()),
                ('cigarettes', models.IntegerField(default=0, null=True)),
                ('working_hours', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.baseuser')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.baseuser',),
        ),
    ]
