# Generated by Django 4.2.2 on 2023-07-05 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_department_company'),
        ('accounts', '0002_alter_manager_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='role',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='subrole',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='company.department'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to='company.company'),
        ),
    ]
