# Generated by Django 4.2.2 on 2023-06-27 15:21

import apps.company.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('description', models.TextField(null=True)),
                ('universal_name', models.CharField(max_length=150, null=True)),
                ('company_type', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('employee_count_range', models.CharField(max_length=100, null=True)),
                ('specialities', models.CharField(max_length=150, null=True)),
                ('location', models.TextField(null=True)),
                ('founded_year', models.CharField(max_length=150, null=True)),
                ('all_over_threshold', models.IntegerField(default=20)),
                ('invitation_paused', models.BooleanField(default=True)),
                ('date_expiration', models.DateField(default=datetime.datetime.utcnow, null=True)),
                ('paid', models.BooleanField(default=True)),
                ('sending_interval', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('description', models.TextField(default='')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.company.models.get_user_media_folder, verbose_name='Avatar')),
                ('logo_name', models.CharField(max_length=255, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
