# Generated by Django 4.2.2 on 2023-07-01 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime.utcnow, null=True),
        ),
    ]
