# Generated by Django 4.2.2 on 2023-06-27 15:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invitations', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(null=True)),
                ('answer', models.TextField(null=True)),
                ('area', models.TextField(null=True)),
                ('score', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('score', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.utcnow, null=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.employee')),
                ('invitation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invitations.invitationinfo')),
            ],
        ),
        migrations.CreateModel(
            name='RpsQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.utcnow, null=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('questionnaire_type', models.CharField(choices=[('', ''), ('', '')], default='', max_length=50, verbose_name='Type')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.questionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='RpsQuestionCategory',
            fields=[
                ('questioncategory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questionnaire.questioncategory')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.rpsquestionnaire')),
            ],
            bases=('questionnaire.questioncategory',),
        ),
        migrations.CreateModel(
            name='RpsQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questionnaire.question')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.rpsquestioncategory')),
            ],
            bases=('questionnaire.question',),
        ),
        migrations.CreateModel(
            name='QuestionHealth',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questionnaire.question')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.questioncategory')),
            ],
            bases=('questionnaire.question',),
        ),
        migrations.CreateModel(
            name='QuestionCategoryQuestionnaire',
            fields=[
                ('questioncategory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questionnaire.questioncategory')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.questionnaire')),
            ],
            bases=('questionnaire.questioncategory',),
        ),
    ]
