# Generated by Django 4.2.2 on 2023-09-26 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0004_alter_baseinvitation_token'),
        ('accounts', '0003_alter_baseuser_role_alter_baseuser_subrole_and_more'),
        ('questionnaire', '0002_alter_questionnaire_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioncategoryquestionnaire',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='questionnaire.questionnaire'),
        ),
        migrations.AlterField(
            model_name='questionhealth',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questionnaire.questioncategory'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionnaires', to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='invitation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionnaires', to='invitations.baseinvitation'),
        ),
        migrations.AlterField(
            model_name='rpsquestion',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RpsQuestions', to='questionnaire.rpsquestioncategory'),
        ),
        migrations.AlterField(
            model_name='rpsquestioncategory',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RpsCategories', to='questionnaire.rpsquestionnaire'),
        ),
        migrations.AlterField(
            model_name='rpsquestionnaire',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rpsquestionnaires', to='questionnaire.questionnaire'),
        ),
    ]
